# 线性代数

## 矩阵操作

使用mat函数创建一个2X3矩阵

In [1]:
import numpy as np
a = np.mat([[1,2,3],[4,5,6]])
a

matrix([[1, 2, 3],
        [4, 5, 6]])

使用shape可以获取矩阵的大小

In [2]:
a.shape

(2L, 3L)

进行转置：

In [3]:
a.T

matrix([[1, 4],
        [2, 5],
        [3, 6]])

实际上官方文档建议我们使用二维数组代替矩阵来进行矩阵运算  
因为二维数组用得较多，而且基本可取代矩阵。比如：可见矩阵和数组基本上都可以

In [4]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

## 矩阵乘法

In [5]:
A=np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
B=np.array([[1,4],[2,5],[3,6]])
B

array([[1, 4],
       [2, 5],
       [3, 6]])

矩阵的数乘

In [7]:
2 * B

array([[ 2,  8],
       [ 4, 10],
       [ 6, 12]])

 dot函数用于矩阵乘法，对于二维数组，它计算的是矩阵乘积，对于一维数组，它计算的是内积

In [8]:
np.dot(A,B)

array([[14, 32],
       [32, 77]])

In [9]:
A.dot(B)

array([[14, 32],
       [32, 77]])

In [10]:
np.dot(B,A)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

创建单位矩阵

In [11]:
I=np.eye(3)
I

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

## 矩阵转置

In [12]:
B=np.array([[1,4],[2,5],[3,6]])
B

array([[1, 4],
       [2, 5],
       [3, 6]])

In [13]:
D=np.array([[0,3],[1,4],[2,5]])
D

array([[0, 3],
       [1, 4],
       [2, 5]])

#### (A±B)'=A'±B

In [14]:
(B + D).T

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [15]:
B.T + D.T

array([[ 1,  3,  5],
       [ 7,  9, 11]])

#### (A×B)'= B'×A'

In [16]:
np.dot(A,B).T

array([[14, 32],
       [32, 77]])

In [17]:
np.dot(B.T, A.T)

array([[14, 32],
       [32, 77]])